import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
const git=(args)=>execFileSync('git',args,{encoding:'utf8',windowsHide:true}).trim();
if(resolve(git(['rev-parse','--show-toplevel']))!==process.cwd())throw Error('Run packaging from the repository root.');
if(git(['status','--porcelain','--untracked-files=normal']))throw Error('Source packaging requires a clean committed tree.');
const metadata=JSON.parse(readFileSync('package.json','utf8'));
const version=metadata.version;
if(metadata.name!=='iris-workbench'||metadata.license!=='MIT'||!/^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/.test(version))throw Error('Expected stable IRIS Workbench version and MIT metadata.');
const commit=git(['rev-parse','HEAD']),tree=git(['rev-parse','HEAD^{tree}']);
if(process.env.GITHUB_SHA&&process.env.GITHUB_SHA!==commit)throw Error('Checkout differs from the workflow commit.');
const image='containers.intersystems.com/intersystems/iris-community@sha256:87c8b9062530093d30384d66caa9933b8399bfbace7ddb7f1bdb983c0bfdb85b';
const specification={repository:'intersystems-community/sysadmin-api-specification',commit:'f764aea427e5c0b1dd08a4c18a0457e0ff7b3b34',path:'mainspec_v2.json',sha256:'1ab154c7c5d9b25e6b227944a44a120c670686f876c2e14abfb9ee5898596650'};
if(!readFileSync('scripts/setup-local.mjs','utf8').includes(image)||!readFileSync('scripts/fetch-spec.mjs','utf8').includes(specification.sha256)||!readFileSync('scripts/fetch-spec.mjs','utf8').includes(specification.commit))throw Error('Manifest upstream inputs differ from the setup scripts.');
const directory=resolve('release-artifacts');mkdirSync(directory,{recursive:true});
const filename=`iris-workbench_${version}_source.zip`,output=resolve(directory,filename);
execFileSync('git',['-c','core.autocrlf=false','archive','--format=zip',`--prefix=iris-workbench-${version}/`,`--output=${output}`,'HEAD'],{windowsHide:true});
const digest=data=>createHash('sha256').update(data).digest('hex');
const bytes=readFileSync(output);
const manifest={repository:'agammann/iris-workbench',version,commit,tree,source:{filename,bytes:bytes.length,sha256:digest(bytes)},requirements:{node:metadata.engines.node,pnpm:metadata.packageManager,docker:'Linux containers',verifiedHost:'Windows 11 x64'},upstream:{image,specification},delivery:'Self-hosted local Node portal; no private state or downloaded specification cache in the source ZIP.'};
const manifestBytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');
writeFileSync(resolve(directory,'release-manifest.json'),manifestBytes);
const checksum=digest(bytes)+'  '+filename+'\n';
writeFileSync(output+'.sha256',checksum);
writeFileSync(resolve(directory,'SHA256SUMS'),checksum+digest(manifestBytes)+'  release-manifest.json\n');
console.log(`Packaged ${filename} from ${commit}`);
