export const resources = {
  apps: {
    title: "Web applications",
    nav: "Apps",
    list: "/v2/web-apps",
    item: "/v2/web-app",
    key: "name",
    id: "Name",
    columns: ["Name", "Namespace", "DispatchClass", "Enabled"],
    featured: [
      "Enabled",
      "NameSpace",
      "DispatchClass",
      "Resource",
      "AutheEnabled",
      "Description",
    ],
    defaults: {
      NameSpace: "USER",
      Enabled: false,
      AutheEnabled: 32,
      Description: "",
    },
    create: "PUT",
  },
  users: {
    title: "Users",
    nav: "Access",
    list: "/v2/security/users",
    item: "/v2/security/user",
    key: "name",
    id: "Name",
    columns: ["Name", "FullName", "Namespace", "Enabled"],
    featured: ["FullName", "Enabled", "Roles", "NameSpace", "Comment"],
    defaults: {
      User: { Enabled: true, ChangePassword: true, Roles: [], FullName: "" },
      Password: "",
    },
    create: "POST",
  },
  roles: {
    title: "Roles",
    nav: "Access",
    list: "/v2/security/roles",
    item: "/v2/security/role",
    key: "name",
    id: "Name",
    columns: ["Name", "Description", "EscalationOnly"],
    featured: ["Description", "Resources", "GrantedRoles", "EscalationOnly"],
    defaults: {
      Description: "",
      Resources: [],
      GrantedRoles: [],
      EscalationOnly: false,
    },
    create: "PUT",
  },
  resources: {
    title: "Resources",
    nav: "Access",
    list: "/v2/security/resources",
    item: "/v2/security/resource",
    key: "name",
    id: "Name",
    columns: ["Name", "Description", "PublicPermission"],
    featured: ["Description", "PublicPermission"],
    defaults: { Description: "", PublicPermission: "" },
    create: "PUT",
  },
  collections: {
    title: "Wallet collections",
    nav: "Security",
    list: "/v2/wallet/collections",
    item: "/v2/wallet/collection",
    key: "name",
    id: "Name",
    columns: ["Name", "EditResource", "UseResource"],
    featured: ["EditResource", "UseResource"],
    defaults: {
      EditResource: "%Admin_Wallet:USE",
      UseResource: "%Admin_Wallet:USE",
    },
    create: "PUT",
  },
  secrets: {
    title: "Secrets",
    nav: "Security",
    list: "/v2/wallet/secrets",
    item: "/v2/wallet/secret",
    key: "name",
    id: "Name",
    columns: ["Name", "Type"],
    featured: ["Type", "WalletSecretConfig"],
    defaults: {
      Type: "%Wallet.KeyValue",
      WalletSecretConfig: {
        AllowedHosts: [],
        RequireTLS: true,
        Usage: ["HTTP"],
        Secret: {},
      },
    },
    create: "PUT",
    noRead: true,
  },
  certificates: {
    title: "Certificates",
    nav: "Security",
    list: "/v2/security/x509-credentials",
    item: "/v2/security/x509-credential",
    key: "alias",
    id: "Alias",
    columns: ["Alias", "OwnerList", "HasPrivateKey"],
    featured: ["OwnerList", "CAFile", "PeerNames"],
    defaults: {
      Alias: "",
      OwnerList: [],
      CertificateFile: "",
      PrivateKeyFile: "",
      PrivateKeyPassword: "",
    },
    create: "POST",
    bodyId: true,
  },
  tls: {
    title: "TLS configurations",
    nav: "Security",
    list: "/v2/security/ssl-configurations",
    item: "/v2/security/ssl-configuration",
    key: "name",
    id: "Name",
    columns: ["Name", "Enabled", "Type"],
    featured: ["Enabled", "Description", "Type", "VerifyPeer", "CAFile"],
    defaults: { Enabled: false, Description: "", Type: 0, VerifyPeer: 1 },
    create: "PUT",
  },
  oauth: {
    title: "OAuth servers",
    nav: "Security",
    list: "/v2/security/oauth2/client/server-definitions",
    item: "/v2/security/oauth2/client/server-definition",
    key: "serverId",
    id: "ID",
    columns: ["ID", "IssuerEndpoint", "ClientCount"],
    featured: [
      "IssuerEndpoint",
      "SSLConfiguration",
      "ServerCredentials",
      "Metadata",
    ],
    defaults: {
      IssuerEndpoint: "https://example.invalid",
      SSLConfiguration: "",
      Metadata: { authorization_endpoint: "", token_endpoint: "" },
    },
    create: "POST",
    autoId: true,
  },
  clients: {
    title: "OAuth clients",
    nav: "Security",
    list: "/v2/security/oauth2/client/client-configurations",
    item: "/v2/security/oauth2/client/client-configuration",
    key: "applicationName",
    id: "ApplicationName",
    columns: ["ApplicationName", "ClientType", "DefaultScope"],
    featured: [
      "ServerDefinition",
      "Enabled",
      "Description",
      "ClientType",
      "SSLConfiguration",
      "RedirectionEndpoint",
      "DefaultScope",
      "Metadata",
    ],
    defaults: {
      ServerDefinition: "",
      Enabled: false,
      ClientType: "confidential",
      SSLConfiguration: "",
      RedirectionEndpoint: "",
      DefaultScope: "",
      Metadata: {},
    },
    create: "PUT",
  },
  tasks: {
    title: "Tasks",
    nav: "Tasks",
    list: "/v2/tasks",
    item: "/v2/task",
    key: "id",
    id: "Id",
    columns: ["Name", "Namespace", "NextScheduled", "Suspended"],
    featured: [
      "Name",
      "Description",
      "TaskClass",
      "NameSpace",
      "RunAsUser",
      "TimePeriod",
      "DailyStartTime",
      "StartDate",
      "Settings",
    ],
    defaults: null,
    create: "POST",
    autoId: true,
  },
  processes: {
    title: "Processes",
    nav: "System",
    list: "/v2/processes",
    item: "/v2/process",
    key: "id",
    id: "Pid",
    columns: ["Pid", "Username", "Nspace", "Routine", "State"],
    readonly: true,
  },
  devices: {
    title: "Devices",
    nav: "System",
    list: "/v2/devices",
    item: "/v2/device",
    key: "name",
    id: "Name",
    columns: ["Name", "Type", "PhysicalDevice", "Description"],
    readonly: true,
  },
  capacity: {
    title: "CPU, memory and disk",
    nav: "System",
    list: "extension:system",
    id: "Name",
    columns: ["Name", "Value"],
    readonly: true,
  },
  metrics: {
    title: "System dashboard",
    nav: "System",
    list: "/v2/monitor/dashboard/main",
    id: "Name",
    columns: ["Name", "Value"],
    readonly: true,
  },
  journal: {
    title: "Journal files",
    nav: "Logs",
    list: "/v2/journal/files",
    id: "Name",
    columns: ["Name", "Size", "CreationTime"],
    readonly: true,
  },
};
export const groups = {
  Apps: ["apps"],
  Access: ["users", "roles", "resources"],
  Security: [
    "collections",
    "secrets",
    "certificates",
    "tls",
    "oauth",
    "clients",
  ],
  Tasks: ["tasks"],
  System: ["processes", "devices", "capacity", "metrics"],
};
export const titles = {
  Workspace: [
    "Keep your instance in hand.",
    "The context to investigate. A clear path to action.",
  ],
  Apps: [
    "Give every app a clear path.",
    "Inspect configuration, access, and the settings that matter.",
  ],
  Access: [
    "Know who can do what.",
    "Users, roles, and the resources that connect them.",
  ],
  Security: [
    "Keep the essentials protected.",
    "Manage secrets, certificates, and trusted connections.",
  ],
  Tasks: [
    "Keep work on schedule.",
    "Inspect definitions, run a task, and follow its history.",
  ],
  System: [
    "See what is running.",
    "Processes, devices, and the state of your instance.",
  ],
  Logs: ["Follow the signal.", "A clear timeline. The context to act."],
  "API explorer": [
    "Go a little deeper.",
    "Inspect documented endpoints with your current IRIS permissions.",
  ],
};
export const sampleEvents = [
  ["18:42:11", "Web application", "/api/orders disabled", "Disabled"],
  ["18:40:02", "Security", "Configuration updated", "Info"],
  ["18:38:45", "Task", "Nightly export finished", "Complete"],
  ["18:35:08", "System", "Journal switched", "Info"],
  ["18:32:16", "Security", "Login succeeded", "Info"],
  ["18:31:55", "Task", "Queue check finished", "Complete"],
].map(([Time, Source, Event, State], i) => ({
  id: String(i),
  Time,
  Source,
  Event,
  State,
  raw: { Application: "/api/orders", Namespace: "USER", Source, State },
  sample: true,
}));
